version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "50090:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_USERNAME: "book_log"
      DB_PASSWORD: "pass"
      DB_DATABASE: "book_log"

  db:
    image: mysql:5.5.62
    ports:
      - "53306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./docker/db/db-variables.env
volumes:
  mysql_data:
